version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - docker-app

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - ./backend/.env 
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - docker-app
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build: 
      context: ./frontend/react-docker-app
      dockerfile: DockerFile  # Double-check if it's Dockerfile or Dockerfile (case-sensitive)
    volumes:
      - ./frontend/react-docker-app:/app
      - /app/node_modules
    networks:
      - docker-app
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mongo_data:

networks:
  docker-app:
    driver: bridge
