services:
  frontend:
    build:
      context: ./frontend/react-docker-app
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react-docker-app:/app
      - /app/node_modules     # Prevents overwriting container modules with host modules
    ports:
      - "5173:5173"